In [27]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\lp109\projects\canasta-inteligente-gt\venv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\lp109\projects\canasta-inteligente-gt\venv\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
from data_loaders.nutrition_table_incap_data_loader import Nutrition_INCAP
incap_data = Nutrition_INCAP("./data/raw/tabladecomposiciondealimentos.pdf")

Loaded data from cache serialized data

In [29]:
# Load data from 2024 - 2026
import pandas as pd

# Load the first sheet into a DataFrame
df_rural = pd.read_excel('./data/raw/cba_historicos/Historico-por-grupo-alimenticio-y-por-producto-CBAR-2024-2026-2-1.xlsx', sheet_name='Histórico producto CBAR', index_col=False)
df_rural.head()

,Año,Mes,Producto,Cantidad base,Unidad de medida base,Kilocalorias diarias,Kilocalorias mensuales,Cantidad gramos diarios,Cantidad gramos mensuales,Costo diario,Costo mensual,Precio según unidad de medida base*
0,2024,Enero,Arroz corriente,454.0,Gramos,61.358637,1840.759113,17.044066,511.321976,0.298271,8.948135,7.945000
1,2024,Enero,Arroz precocido,454.0,Gramos,11.877317,356.319524,3.125610,93.768296,0.057824,1.734713,8.399000
2,2024,Enero,Maíz blanco,454.0,Gramos,287.996160,8639.884810,78.903058,2367.091729,0.434488,13.034646,2.500000
3,2024,Enero,Harina de maíz,454.0,Gramos,44.918127,1347.543820,12.442695,373.280837,0.171087,5.132612,6.242500
4,2024,Enero,Harina para atoles,454.0,Gramos,17.359381,520.781424,4.653989,139.619685,0.113764,3.412926,11.097778

In [30]:
df_rural.columns

Index(['Año', 'Mes', 'Producto', 'Cantidad base', 'Unidad de medida base',
       'Kilocalorias diarias', 'Kilocalorias mensuales',
       'Cantidad gramos diarios', 'Cantidad gramos mensuales', 'Costo diario',
       'Costo mensual', 'Precio según unidad de medida base*'],
      dtype='str')

In [31]:
rows_with_nan = df_rural[df_rural.isna().any(axis=1)]

rows_with_nan

,Año,Mes,Producto,Cantidad base,Unidad de medida base,Kilocalorias diarias,Kilocalorias mensuales,Cantidad gramos diarios,Cantidad gramos mensuales,Costo diario,Costo mensual,Precio según unidad de medida base*
1680,*Precio según la unidad de medida base estable...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df_rural.shape

(1681, 12)

In [33]:
df_rural = df_rural.dropna()
df_rural.shape

(1680, 12)

In [34]:
from dtos.Product import Product, Products

products = Products(regions=['urbana', 'republica', 'rural'])
current_region = 'rural'
for index, row in df_rural.iterrows(): 
    result = incap_data.search_word_matches(str(row["Producto"]).lower(), target_field='nombre', top_n=1, min_probability=.5)
    energy_per_100g_kcal = 100 * row["Kilocalorias diarias"] / row["Cantidad gramos diarios"]
    cost_per_gram = row["Costo diario"] / row["Cantidad gramos diarios"]
    days_in_month = row['Cantidad gramos mensuales']/ row["Cantidad gramos diarios"]
    
    
    products.add_data(
        current_region, 
        row["Producto"], 
        energy_per_100g_kcal, 
        row["Año"],
        row["Mes"],
        cost_per_gram,
        row['Kilocalorias diarias'],
        row['Cantidad gramos diarios'],
        days_in_month,
        row['Cantidad base'],
        row['Costo diario'],
        result[0][0] if result else None, 
        "Search Word matches with min prob 50%" if result else None,
        result[0][1] if result else None, 
    )

Nuevo producto creado para Arroz corriente ; 2024, Enero
Nuevo producto creado para Arroz precocido ; 2024, Enero
Nuevo producto creado para Maíz blanco ; 2024, Enero
Nuevo producto creado para Harina de maíz ; 2024, Enero
Nuevo producto creado para Harina para atoles  ; 2024, Enero
Nuevo producto creado para Pan francés ; 2024, Enero
Nuevo producto creado para Pan dulce ; 2024, Enero
Nuevo producto creado para Galletas dulces ; 2024, Enero
Nuevo producto creado para Tortillas frescas ; 2024, Enero
Nuevo producto creado para Avena/mosh ; 2024, Enero
Nuevo producto creado para Espagueti ; 2024, Enero
Nuevo producto creado para Fideos en todas sus formas (Excepto macarrones y espagueti) ; 2024, Enero
Nuevo producto creado para Carne de res sin hueso (posta) ; 2024, Enero
Nuevo producto creado para Carne de res con hueso para cocido ; 2024, Enero
Nuevo producto creado para Carne de pollo blanco ; 2024, Enero
Nuevo producto creado para Carne de pollo amarillo  ; 2024, Enero
Nuevo producto creado para Salchichas y productos similares de carne ; 2024, Enero
Nuevo producto creado para Longanizas y chorizos (de todo tipo) ; 2024, Enero
Nuevo producto creado para Pescado entero, fresco, refrigerado o congelado ; 2024, Enero
Nuevo producto creado para Leche en polvo ; 2024, Enero
Nuevo producto creado para Crema artesanal ; 2024, Enero
Nuevo producto creado para Queso fresco (Incluye el queso supercremoso) ; 2024, Enero
Nuevo producto creado para Huevos de gallina de granja ; 2024, Enero
Nuevo producto creado para Aceite vegetal mixtos ; 2024, Enero
Nuevo producto creado para Margarina vegetal regular ; 2024, Enero
Nuevo producto creado para Aguacates frescos ; 2024, Enero
Nuevo producto creado para Bananos frescos ; 2024, Enero
Nuevo producto creado para Plátanos frescos ; 2024, Enero
Nuevo producto creado para Limones y limas frescas ; 2024, Enero
Nuevo producto creado para Naranjas frescas ; 2024, Enero
Nuevo producto creado para Manzanas frescas ; 2024, Enero
Nuevo producto creado para Repollo, fresco o refrigerado ; 2024, Enero
Nuevo producto creado para Cilantro, perejil y hierbabuena ; 2024, Enero
Nuevo producto creado para Macuy/Hierba mora/Quilete ; 2024, Enero
Nuevo producto creado para Chile pimiento fresco ; 2024, Enero
Nuevo producto creado para Pepinos y pepinillos, frescos o refrigerados ; 2024, Enero
Nuevo producto creado para Tomate fresco ; 2024, Enero
Nuevo producto creado para Güisquil ; 2024, Enero
Nuevo producto creado para Zanahorias ; 2024, Enero
Nuevo producto creado para Cebollas ; 2024, Enero
Nuevo producto creado para Papas ; 2024, Enero
Nuevo producto creado para Frijoles negros, secos ; 2024, Enero
Nuevo producto creado para Frijoles preparados, procesados y condimentados (enlatados o empaquetados) ; 2024, Enero
Nuevo producto creado para Azúcar de caña blanca ; 2024, Enero
Nuevo producto creado para Dulces en general (incluye paletas, bombones, gomitas) ; 2024, Enero
Nuevo producto creado para Sopas instantáneas (Vaso y bolsa) ; 2024, Enero
Nuevo producto creado para Sal ; 2024, Enero
Nuevo producto creado para Consomé ; 2024, Enero
Nuevo producto creado para Salsa de tomate (Ranchera, Queso etc.) ; 2024, Enero
Nuevo producto creado para Bases para sopas  ; 2024, Enero
Nuevo producto creado para Snacks (excluye papalinas, plataninas, yucas, malangas, etc.) ; 2024, Enero
Nuevo producto creado para Jugos de frutas líquidos  ; 2024, Enero
Nuevo producto creado para Café molido ; 2024, Enero
Nuevo producto creado para Café instantáneo ; 2024, Enero
Nuevo producto creado para Agua purificada ; 2024, Enero
Nuevo producto creado para Gaseosas ; 2024, Enero
Nuevo producto creado para Desayuno o cena continental (bebida y dos acompañamientos elaborados) ; 2024, Enero
Nuevo producto creado para Almuerzo o cena simple (bebida, carne de pollo y acompañamiento) excluye gaseosa ; 2024, Enero
Nuevo producto creado para Tamales y paches  ; 2024, Enero
Nuevo producto creado para Piezas de pollo individual o entero (sin acompañamiento) ; 2024, Enero
Producto (Arroz corriente ; 2024, Febrero ) agredado a timeline de Producto existente Arroz corriente
Producto (Arroz precocido ; 2024, Febrero ) agredado a timeline de Producto existente Arroz precocido
Producto (Maíz blanco ; 2024, Febrero ) agredado a timeline de Producto existente Maíz blanco
Producto (Harina de maíz ; 2024, Febrero ) agredado a timeline de Producto existente Harina de maíz
Producto (Harina para atoles  ; 2024, Febrero ) agredado a timeline de Producto existente Harina para atoles
Producto (Pan francés ; 2024, Febrero ) agredado a timeline de Producto existente Pan francés
Producto (Pan dulce ; 2024, Febrero ) agredado a timeline de Producto existente Pan dulce
Producto (Galletas dulces ; 2024, Febrero ) agredado a timeline de Producto existente Galletas dulces
Producto (Tortillas frescas ; 2024, Febrero ) agredado a timeline de Producto existente Tortillas frescas
Producto (Avena/mosh ; 2024, Febrero ) agredado a timeline de Producto existente Avena/mosh
Producto (Espagueti ; 2024, Febrero ) agredado a timeline de Producto existente Espagueti
Producto (Fideos en todas sus formas (Excepto macarrones y espagueti) ; 2024, Febrero ) agredado a timeline de Producto existente Fideos en todas sus formas (Excepto macarrones y espagueti)
Producto (Carne de res sin hueso (posta) ; 2024, Febrero ) agredado a timeline de Producto existente Carne de res sin hueso (posta)
Producto (Carne de res con hueso para cocido ; 2024, Febrero ) agredado a timeline de Producto existente Carne de res con hueso para cocido
Producto (Carne de pollo blanco ; 2024, Febrero ) agredado a timeline de Producto existente Carne de pollo blanco
Producto (Carne de pollo amarillo  ; 2024, Febrero ) agredado a timeline de Producto existente Carne de pollo amarillo
Producto (Salchichas y productos similares de carne ; 2024, Febrero ) agredado a timeline de Producto existente Salchichas y productos similares de carne
Producto (Longanizas y chorizos (de todo tipo) ; 2024, Febrero ) agredado a timeline de Producto existente Longanizas y chorizos (de todo tipo)
Producto (Pescado entero, fresco, refrigerado o congelado ; 2024, Febrero ) agredado a timeline de Producto existente Pescado entero, fresco, refrigerado o congelado
Producto (Leche en polvo ; 2024, Febrero ) agredado a timeline de Producto existente Leche en polvo
Producto (Crema artesanal ; 2024, Febrero ) agredado a timeline de Producto existente Crema artesanal
Producto (Queso fresco (Incluye el queso supercremoso) ; 2024, Febrero ) agredado a timeline de Producto existente Queso fresco (Incluye el queso supercremoso)
Producto (Huevos de gallina de granja ; 2024, Febrero ) agredado a timeline de Producto existente Huevos de gallina de granja
Producto (Aceite vegetal mixtos ; 2024, Febrero ) agredado a timeline de Producto existente Aceite vegetal mixtos
Producto (Margarina vegetal regular ; 2024, Febrero ) agredado a timeline de Producto existente Margarina vegetal regular
Producto (Aguacates frescos ; 2024, Febrero ) agredado a timeline de Producto existente Aguacates frescos
Producto (Bananos frescos ; 2024, Febrero ) agredado a timeline de Producto existente Bananos frescos
Producto (Plátanos frescos ; 2024, Febrero ) agredado a timeline de Producto existente Plátanos frescos
Producto (Limones y limas frescas ; 2024, Febrero ) agredado a timeline de Producto existente Limones y limas frescas
Producto (Naranjas frescas ; 2024, Febrero ) agredado a timeline de Producto existente Naranjas frescas
Producto (Manzanas frescas ; 2024, Febrero ) agredado a timeline de Producto existente Manzanas frescas
Producto (Repollo, fresco o refrigerado ; 2024, Febrero ) agredado a timeline de Producto existente Repollo, fresco o refrigerado
Producto (Cilantro, perejil y hierbabuena ; 2024, Febrero ) agredado a timeline de Producto existente Cilantro, perejil y hierbabuena
Producto (Macuy/Hierba mora/Quilete ; 2024, Febrero ) agredado a timeline de Producto existente Macuy/Hierba mora/Quilete
Producto (Chile pimiento fresco ; 2024, Febrero ) agredado a timeline de Producto existente Chile pimiento fresco
Producto (Pepinos y pepinillos, frescos o refrigerados ; 2024, Febrero ) agredado a timeline de Producto existente Pepinos y pepinillos, frescos o refrigerados
Producto (Tomate fresco ; 2024, Febrero ) agredado a timeline de Producto existente Tomate fresco
Producto (Güisquil ; 2024, Febrero ) agredado a timeline de Producto existente Güisquil
Producto (Zanahorias ; 2024, Febrero ) agredado a timeline de Producto existente Zanahorias
Producto (Cebollas ; 2024, Febrero ) agredado a timeline de Producto existente Cebollas
Producto (Papas ; 2024, Febrero ) agredado a timeline de Producto existente Papas
Producto (Frijoles negros, secos ; 2024, Febrero ) agredado a timeline de Producto existente Frijoles negros, secos
Producto (Frijoles preparados, procesados y condimentados (enlatados o empaquetados) ; 2024, Febrero ) agredado a timeline de Producto existente Frijoles preparados, procesados y condimentados (enlatados o empaquetados)
Producto (Azúcar de caña blanca ; 2024, Febrero ) agredado a timeline de Producto existente Azúcar de caña blanca
Producto (Dulces en general (incluye paletas, bombones, gomitas) ; 2024, Febrero ) agredado a timeline de Producto existente Dulces en general (incluye paletas, bombones, gomitas)
Producto (Sopas instantáneas (Vaso y bolsa) ; 2024, Febrero ) agredado a timeline de Producto existente Sopas instantáneas (Vaso y bolsa)
Producto (Sal ; 2024, Febrero ) agredado a timeline de Producto existente Sal
Producto (Consomé ; 2024, Febrero ) agredado a timeline de Producto existente Consomé
Producto (Salsa de tomate (Ranchera, Queso etc.) ; 2024, Febrero ) agredado a timeline de Producto existente Salsa de tomate (Ranchera, Queso etc.)
Producto (Bases para sopas  ; 2024, Febrero ) agredado a timeline de Producto existente Bases para sopas
Producto (Snacks (excluye papalinas, plataninas, yucas, malangas, etc.) ; 2024, Febrero ) agredado a timeline de Producto existente Snacks (excluye papalinas, plataninas, yucas, malangas, etc.)
Producto (Jugos de frutas líquidos  ; 2024, Febrero ) agredado a timeline de Producto existente Jugos de frutas líquidos
Producto (Café molido ; 2024, Febrero ) agredado a timeline de Producto existente Café molido
Producto (Café instantáneo ; 2024, Febrero ) agredado a timeline de Producto existente Café instantáneo
Producto (Agua purificada ; 2024, Febrero ) agredado a timeline de Producto existente Agua purificada
Producto (Gaseosas ; 2024, Febrero ) agredado a timeline de Producto existente Gaseosas
Producto (Desayuno o cena continental (bebida y dos acompañamientos elaborados) ; 2024, Febrero ) agredado a timeline de Producto existente Desayuno o cena continental (bebida y dos acompañamientos elaborados)
Producto (Almuerzo o cena simple (bebida, carne de pollo y acompañamiento) excluye gaseosa ; 2024, Febrero ) agredado a timeline de Producto existente Almuerzo o cena simple (bebida, carne de pollo y acompañamiento) excluye gaseosa
Producto (Tamales y paches  ; 2024, Febrero ) agredado a timeline de Producto existente Tamales y paches
Producto (Piezas de pollo individual o entero (sin acompañamiento) ; 2024, Febrero ) agredado a timeline de Producto existente Piezas de pollo individual o entero (sin acompañamiento)
Producto (Arroz corriente ; 2024, Marzo ) agredado a timeline de Producto existente Arroz corriente
Producto (Arroz precocido ; 2024, Marzo ) agredado a timeline de Producto existente Arroz precocido
Producto (Maíz blanco ; 2024, Marzo ) agredado a timeline de Producto existente Maíz blanco
Producto (Harina de maíz ; 2024, Marzo ) agredado a timeline de Producto existente Harina de maíz
Producto (Harina para atoles  ; 2024, Marzo ) agredado a timeline de Producto existente Harina para atoles
Producto (Pan francés ; 2024, Marzo ) agredado a timeline de Producto existente Pan francés
Producto (Pan dulce ; 2024, Marzo ) agredado a timeline de Producto existente Pan dulce
Producto (Galletas dulces ; 2024, Marzo ) agredado a timeline de Producto existente Galletas dulces
Producto (Tortillas frescas ; 2024, Marzo ) agredado a timeline de Producto existente Tortillas frescas
Producto (Avena/mosh ; 2024, Marzo ) agredado a timeline de Producto existente Avena/mosh
Producto (Espagueti ; 2024, Marzo ) agredado a timeline de Producto existente Espagueti
Producto (Fideos en todas sus formas (Excepto macarrones y espagueti) ; 2024, Marzo ) agredado a timeline de Producto existente Fideos en todas sus formas (Excepto macarrones y espagueti)
Producto (Carne de res sin hueso (posta) ; 2024, Marzo ) agredado a timeline de Producto existente Carne de res sin hueso (posta)
Producto (Carne de res con hueso para cocido ; 2024, Marzo ) agredado a timeline de Producto existente Carne de res con hueso para cocido
Producto (Carne de pollo blanco ; 2024, Marzo ) agredado a timeline de Producto existente Carne de pollo blanco
Producto (Carne de pollo amarillo  ; 2024, Marzo ) agredado a timeline de Producto existente Carne de pollo amarillo
Producto (Salchichas y productos similares de carne ; 2024, Marzo ) agredado a timeline de Producto existente Salchichas y productos similares de carne
Producto (Longanizas y chorizos (de todo tipo) ; 2024, Marzo ) agredado a timeline de Producto existente Longanizas y chorizos (de todo tipo)
Producto (Pescado entero, fresco, refrigerado o congelado ; 2024, Marzo ) agredado a timeline de Producto existente Pescado entero, fresco, refrigerado o congelado
Producto (Leche en polvo ; 2024, Marzo ) agredado a timeline de Producto existente Leche en polvo
Producto (Crema artesanal ; 2024, Marzo ) agredado a timeline de Producto existente Crema artesanal
Producto (Queso fresco (Incluye el queso supercremoso) ; 2024, Marzo ) agredado a timeline de Producto existente Queso fresco (Incluye el queso supercremoso)
Producto (Huevos de gallina de granja ; 2024, Marzo ) agredado a timeline de Producto existente Huevos de gallina de granja
Producto (Aceite vegetal mixtos ; 2024, Marzo ) agredado a timeline de Producto existente Aceite vegetal mixtos
Producto (Margarina vegetal regular ; 2024, Marzo ) agredado a timeline de Producto existente Margarina vegetal regular
Producto (Aguacates frescos ; 2024, Marzo ) agredado a timeline de Producto existente Aguacates frescos
Producto (Bananos frescos ; 2024, Marzo ) agredado a timeline de Producto existente Bananos frescos
Producto (Plátanos frescos ; 2024, Marzo ) agredado a timeline de Producto existente Plátanos frescos
Producto (Limones y limas frescas ; 2024, Marzo ) agredado a timeline de Producto existente Limones y limas frescas
Producto (Naranjas frescas ; 2024, Marzo ) agredado a timeline de Producto existente Naranjas frescas
Producto (Manzanas frescas ; 2024, Marzo ) agredado a timeline de Producto existente Manzanas frescas
Producto (Repollo, fresco o refrigerado ; 2024, Marzo ) agredado a timeline de Producto existente Repollo, fresco o refrigerado
Producto (Cilantro, perejil y hierbabuena ; 2024, Marzo ) agredado a timeline de Producto existente Cilantro, perejil y hierbabuena
Producto (Macuy/Hierba mora/Quilete ; 2024, Marzo ) agredado a timeline de Producto existente Macuy/Hierba mora/Quilete
Producto (Chile pimiento fresco ; 2024, Marzo ) agredado a timeline de Producto existente Chile pimiento fresco
Producto (Pepinos y pepinillos, frescos o refrigerados ; 2024, Marzo ) agredado a timeline de Producto existente Pepinos y pepinillos, frescos o refrigerados
Producto (Tomate fresco ; 2024, Marzo ) agredado a timeline de Producto existente Tomate fresco
Producto (Güisquil ; 2024, Marzo ) agredado a timeline de Producto existente Güisquil
Producto (Zanahorias ; 2024, Marzo ) agredado a timeline de Producto existente Zanahorias
Producto (Cebollas ; 2024, Marzo ) agredado a timeline de Producto existente Cebollas
Producto (Papas ; 2024, Marzo ) agredado a timeline de Producto existente Papas
Producto (Frijoles negros, secos ; 2024, Marzo ) agredado a timeline de Producto existente Frijoles negros, secos
Producto (Frijoles preparados, procesados y condimentados (enlatados o empaquetados) ; 2024, Marzo ) agredado a timeline de Producto existente Frijoles preparados, procesados y condimentados (enlatados o empaquetados)
Producto (Azúcar de caña blanca ; 2024, Marzo ) agredado a timeline de Producto existente Azúcar de caña blanca
Producto (Dulces en general (incluye paletas, bombones, gomitas) ; 2024, Marzo ) agredado a timeline de Producto existente Dulces en general (incluye paletas, bombones, gomitas)
Producto (Sopas instantáneas (Vaso y bolsa) ; 2024, Marzo ) agredado a timeline de Producto existente Sopas instantáneas (Vaso y bolsa)
Producto (Sal ; 2024, Marzo ) agredado a timeline de Producto existente Sal
Producto (Consomé ; 2024, Marzo ) agredado a timeline de Producto existente Consomé
Producto (Salsa de tomate (Ranchera, Queso etc.) ; 2024, Marzo ) agredado a timeline de Producto existente Salsa de tomate (Ranchera, Queso etc.)
Producto (Bases para sopas  ; 2024, Marzo ) agredado a timeline de Producto existente Bases para sopas
Producto (Snacks (excluye papalinas, plataninas, yucas, malangas, etc.) ; 2024, Marzo ) agredado a timeline de Producto existente Snacks (excluye papalinas, plataninas, yucas, malangas, etc.)
Producto (Jugos de frutas líquidos  ; 2024, Marzo ) agredado a timeline de Producto existente Jugos de frutas líquidos
Producto (Café molido ; 2024, Marzo ) agredado a timeline de Producto existente Café molido
Producto (Café instantáneo ; 2024, Marzo ) agredado a timeline de Producto existente Café instantáneo
Producto (Agua purificada ; 2024, Marzo ) agredado a timeline de Producto existente Agua purificada
Producto (Gaseosas ; 2024, Marzo ) agredado a timeline de Producto existente Gaseosas
Producto (Desayuno o cena continental (bebida y dos acompañamientos elaborados) ; 2024, Marzo ) agredado a timeline de Producto existente Desayuno o cena continental (bebida y dos acompañamientos elaborados)
Producto (Almuerzo o cena simple (bebida, carne de pollo y acompañamiento) excluye gaseosa ; 2024, Marzo ) agredado a timeline de Producto existente Almuerzo o cena simple (bebida, carne de pollo y acompañamiento) excluye gaseosa
Producto (Tamales y paches  ; 2024, Marzo ) agredado a timeline de Producto existente Tamales y paches
Producto (Piezas de pollo individual o entero (sin acompañamiento) ; 2024, Marzo ) agredado a timeline de Producto existente Piezas de pollo individual o entero (sin acompañamiento)
Producto (Arroz corriente ; 2024, Abril ) agredado a timeline de Producto existente Arroz corriente
Producto (Arroz precocido ; 2024, Abril ) agredado a timeline de Producto existente Arroz precocido
Producto (Maíz blanco ; 2024, Abril ) agredado a timeline de Producto existente Maíz blanco
Producto (Harina de maíz ; 2024, Abril ) agredado a timeline de Producto existente Harina de maíz
Producto (Harina para atoles  ; 2024, Abril ) agredado a timeline de Producto existente Harina para atoles
Producto (Pan francés ; 2024, Abril ) agredado a timeline de Producto existente Pan francés
Producto (Pan dulce ; 2024, Abril ) agredado a timeline de Producto existente Pan dulce
Producto (Galletas dulces ; 2024, Abril ) agredado a timeline de Producto existente Galletas dulces
Producto (Tortillas frescas ; 2024, Abril ) agredado a timeline de Producto existente Tortillas frescas
Producto (Avena/mosh ; 2024, Abril ) agredado a timeline de Producto existente Avena/mosh
Producto (Espagueti ; 2024, Abril ) agredado a timeline de Producto existente Espagueti
Producto (Fideos en todas sus formas (Excepto macarrones y espagueti) ; 2024, Abril ) agredado a timeline de Producto existente Fideos en todas sus formas (Excepto macarrones y espagueti)
Producto (Carne de res sin hueso (posta) ; 2024, Abril ) agredado a timeline de Producto existente Carne de res sin hueso (posta)

In [35]:
df_urbano = pd.read_excel('./data/raw/cba_historicos/Historico-por-grupo-alimenticio-y-por-producto-CBAU-2024-2026.xlsx', sheet_name='Histórico producto CBAU', index_col=False)
df_urbano.head()

,Año,Mes,Producto,Cantidad base,Unidad de medida base,Kilocalorías diarias,Kilocalorías mensuales,Cantidad gramos diarios,Cantidad gramos mensuales,Costo diario,Costo mensual,Precio según unidad de medida base*
0,2024,Enero,Arroz corriente,454.0,Gramos,66.715985,2001.479553,18.532218,555.966542,0.324314,9.729414,7.945000
1,2024,Enero,Arroz precocido,454.0,Gramos,22.246412,667.392371,5.854319,175.629571,0.108305,3.249147,8.399000
2,2024,Enero,Pan francés,454.0,Gramos,150.071298,4502.138948,54.177364,1625.320920,1.135001,34.050019,9.511173
3,2024,Enero,Pan dulce,454.0,Gramos,135.949815,4078.494449,37.043546,1111.306389,0.700037,21.001118,8.579549
4,2024,Enero,Galletas dulces,454.0,Gramos,6.280560,188.416796,1.330627,39.918813,0.065367,1.961012,22.302750

In [36]:
rows_with_nan = df_urbano[df_urbano.isna().any(axis=1)]

rows_with_nan

,Año,Mes,Producto,Cantidad base,Unidad de medida base,Kilocalorías diarias,Kilocalorías mensuales,Cantidad gramos diarios,Cantidad gramos mensuales,Costo diario,Costo mensual,Precio según unidad de medida base*
1848,*Precio según la unidad de medida base estable...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
df_urbano.shape

(1849, 12)

In [38]:
df_urbano = df_urbano.dropna()
df_urbano.shape

(1848, 12)

In [39]:
current_region = 'urbana'
for index, row in df_urbano.iterrows(): 
    result = incap_data.search_word_matches(str(row["Producto"]).lower(), target_field='nombre', top_n=1, min_probability=.5)
    energy_per_100g_kcal = 100 * row["Kilocalorías diarias"] / row["Cantidad gramos diarios"]
    cost_per_gram = row["Costo diario"] / row["Cantidad gramos diarios"]
    days_in_month = row['Cantidad gramos mensuales']/ row["Cantidad gramos diarios"]

    
    products.add_data(
        current_region, 
        row["Producto"], 
        energy_per_100g_kcal, 
        row["Año"],
        row["Mes"],
        cost_per_gram,
        row['Kilocalorías diarias'],
        row['Cantidad gramos diarios'],
        days_in_month,
        row['Cantidad base'],
        row['Costo diario'],
        result[0][0] if result else None, 
        "Search Word matches with min prob 50%" if result else None,
        result[0][1] if result else None, 
    )

Nuevo producto creado para Arroz corriente ; 2024, Enero
Nuevo producto creado para Arroz precocido ; 2024, Enero
Nuevo producto creado para Pan francés ; 2024, Enero
Nuevo producto creado para Pan dulce ; 2024, Enero
Nuevo producto creado para Galletas dulces ; 2024, Enero
Nuevo producto creado para Tortillas frescas ; 2024, Enero
Nuevo producto creado para Cereales de bolsa o caja ; 2024, Enero
Nuevo producto creado para Espagueti ; 2024, Enero
Nuevo producto creado para Fideos en todas sus formas (Excepto macarrones y espagueti) ; 2024, Enero
Nuevo producto creado para Carne de res molida ; 2024, Enero
Nuevo producto creado para Carne de res para asar (con y sin hueso) ; 2024, Enero
Nuevo producto creado para Carne de res sin hueso (posta) ; 2024, Enero
Nuevo producto creado para Carne de res con hueso para cocido ; 2024, Enero
Nuevo producto creado para Posta de cerdo sin hueso  ; 2024, Enero
Nuevo producto creado para Carne de pollo blanco ; 2024, Enero
Nuevo producto creado para Carne de pollo amarillo  ; 2024, Enero
Nuevo producto creado para Salchichas y productos similares de carne ; 2024, Enero
Nuevo producto creado para Jamón (pollo, res, cerdo, mixto, etc.) ; 2024, Enero
Nuevo producto creado para Longanizas y chorizos (de todo tipo) ; 2024, Enero
Nuevo producto creado para Leche entera líquida industrializada ; 2024, Enero
Nuevo producto creado para Crema artesanal ; 2024, Enero
Nuevo producto creado para Crema industrializada ; 2024, Enero
Nuevo producto creado para Queso fresco (Incluye el queso supercremoso) ; 2024, Enero
Nuevo producto creado para Huevos de gallina de granja ; 2024, Enero
Nuevo producto creado para Aceite vegetal mixtos ; 2024, Enero
Nuevo producto creado para Margarina vegetal regular ; 2024, Enero
Nuevo producto creado para Aguacates frescos ; 2024, Enero
Nuevo producto creado para Bananos frescos ; 2024, Enero
Nuevo producto creado para Plátanos frescos ; 2024, Enero
Nuevo producto creado para Papayas frescas ; 2024, Enero
Nuevo producto creado para Limones y limas frescas ; 2024, Enero
Nuevo producto creado para Manzanas frescas ; 2024, Enero
Nuevo producto creado para Lechuga, achicoria y rúgula, fresca o refrigerada ; 2024, Enero
Nuevo producto creado para Apio  ; 2024, Enero
Nuevo producto creado para Cilantro, perejil y hierbabuena ; 2024, Enero
Nuevo producto creado para Macuy/Hierba mora/Quilete ; 2024, Enero
Nuevo producto creado para Chile pimiento fresco ; 2024, Enero
Nuevo producto creado para Pepinos y pepinillos, frescos o refrigerados ; 2024, Enero
Nuevo producto creado para Tomate fresco ; 2024, Enero
Nuevo producto creado para Güisquil ; 2024, Enero
Nuevo producto creado para Zanahorias ; 2024, Enero
Nuevo producto creado para Cebollas ; 2024, Enero
Nuevo producto creado para Verduras frescas o refrigeradas limpias y cortadas (excluye las ensaladas) ; 2024, Enero
Nuevo producto creado para Papas ; 2024, Enero
Nuevo producto creado para Frijoles negros, secos ; 2024, Enero
Nuevo producto creado para Frijoles preparados, procesados y condimentados (enlatados o empaquetados) ; 2024, Enero
Nuevo producto creado para Azúcar de caña blanca ; 2024, Enero
Nuevo producto creado para Azúcar de caña morena ; 2024, Enero
Nuevo producto creado para Sopas instantáneas (Vaso y bolsa) ; 2024, Enero
Nuevo producto creado para Sal ; 2024, Enero
Nuevo producto creado para Consomé ; 2024, Enero
Nuevo producto creado para Salsa de tomate (Ranchera, Queso etc.) ; 2024, Enero
Nuevo producto creado para Mayonesa  ; 2024, Enero
Nuevo producto creado para Bases para sopas  ; 2024, Enero
Nuevo producto creado para Snacks (excluye papalinas, plataninas, yucas, malangas, etc.) ; 2024, Enero
Nuevo producto creado para Jugos de frutas líquidos  ; 2024, Enero
Nuevo producto creado para Jugos de frutas en polvo ; 2024, Enero
Nuevo producto creado para Café molido ; 2024, Enero
Nuevo producto creado para Café instantáneo ; 2024, Enero
Nuevo producto creado para Agua purificada ; 2024, Enero
Nuevo producto creado para Gaseosas ; 2024, Enero
Nuevo producto creado para Desayuno o cena continental (bebida y dos acompañamientos elaborados) ; 2024, Enero
Nuevo producto creado para Almuerzo o cena simple (bebida, carne de pollo y acompañamiento) excluye gaseosa ; 2024, Enero
Nuevo producto creado para Tamales y paches  ; 2024, Enero
Nuevo producto creado para Piezas de pollo individual o entero (sin acompañamiento) ; 2024, Enero
Nuevo producto creado para Atoles ; 2024, Enero
Producto (Arroz corriente ; 2024, Febrero ) agredado a timeline de Producto existente Arroz corriente
Producto (Arroz precocido ; 2024, Febrero ) agredado a timeline de Producto existente Arroz precocido
Producto (Pan francés ; 2024, Febrero ) agredado a timeline de Producto existente Pan francés
Producto (Pan dulce ; 2024, Febrero ) agredado a timeline de Producto existente Pan dulce
Producto (Galletas dulces ; 2024, Febrero ) agredado a timeline de Producto existente Galletas dulces
Producto (Tortillas frescas ; 2024, Febrero ) agredado a timeline de Producto existente Tortillas frescas
Producto (Cereales de bolsa o caja ; 2024, Febrero ) agredado a timeline de Producto existente Cereales de bolsa o caja
Producto (Espagueti ; 2024, Febrero ) agredado a timeline de Producto existente Espagueti
Producto (Fideos en todas sus formas (Excepto macarrones y espagueti) ; 2024, Febrero ) agredado a timeline de Producto existente Fideos en todas sus formas (Excepto macarrones y espagueti)
Producto (Carne de res molida ; 2024, Febrero ) agredado a timeline de Producto existente Carne de res molida
Producto (Carne de res para asar (con y sin hueso) ; 2024, Febrero ) agredado a timeline de Producto existente Carne de res para asar (con y sin hueso)
Producto (Carne de res sin hueso (posta) ; 2024, Febrero ) agredado a timeline de Producto existente Carne de res sin hueso (posta)
Producto (Carne de res con hueso para cocido ; 2024, Febrero ) agredado a timeline de Producto existente Carne de res con hueso para cocido
Producto (Posta de cerdo sin hueso  ; 2024, Febrero ) agredado a timeline de Producto existente Posta de cerdo sin hueso
Producto (Carne de pollo blanco ; 2024, Febrero ) agredado a timeline de Producto existente Carne de pollo blanco
Producto (Carne de pollo amarillo  ; 2024, Febrero ) agredado a timeline de Producto existente Carne de pollo amarillo
Producto (Salchichas y productos similares de carne ; 2024, Febrero ) agredado a timeline de Producto existente Salchichas y productos similares de carne
Producto (Jamón (pollo, res, cerdo, mixto, etc.) ; 2024, Febrero ) agredado a timeline de Producto existente Jamón (pollo, res, cerdo, mixto, etc.)
Producto (Longanizas y chorizos (de todo tipo) ; 2024, Febrero ) agredado a timeline de Producto existente Longanizas y chorizos (de todo tipo)
Producto (Leche entera líquida industrializada ; 2024, Febrero ) agredado a timeline de Producto existente Leche entera líquida industrializada
Producto (Crema artesanal ; 2024, Febrero ) agredado a timeline de Producto existente Crema artesanal
Producto (Crema industrializada ; 2024, Febrero ) agredado a timeline de Producto existente Crema industrializada
Producto (Queso fresco (Incluye el queso supercremoso) ; 2024, Febrero ) agredado a timeline de Producto existente Queso fresco (Incluye el queso supercremoso)
Producto (Huevos de gallina de granja ; 2024, Febrero ) agredado a timeline de Producto existente Huevos de gallina de granja
Producto (Aceite vegetal mixtos ; 2024, Febrero ) agredado a timeline de Producto existente Aceite vegetal mixtos
Producto (Margarina vegetal regular ; 2024, Febrero ) agredado a timeline de Producto existente Margarina vegetal regular
Producto (Aguacates frescos ; 2024, Febrero ) agredado a timeline de Producto existente Aguacates frescos
Producto (Bananos frescos ; 2024, Febrero ) agredado a timeline de Producto existente Bananos frescos
Producto (Plátanos frescos ; 2024, Febrero ) agredado a timeline de Producto existente Plátanos frescos
Producto (Papayas frescas ; 2024, Febrero ) agredado a timeline de Producto existente Papayas frescas
Producto (Limones y limas frescas ; 2024, Febrero ) agredado a timeline de Producto existente Limones y limas frescas
Producto (Manzanas frescas ; 2024, Febrero ) agredado a timeline de Producto existente Manzanas frescas
Producto (Lechuga, achicoria y rugula, fresca o refrigerada ; 2024, Febrero ) agredado a timeline de Producto existente Lechuga, achicoria y rúgula, fresca o refrigerada
Producto (Apio  ; 2024, Febrero ) agredado a timeline de Producto existente Apio
Producto (Cilantro, perejil y hierbabuena ; 2024, Febrero ) agredado a timeline de Producto existente Cilantro, perejil y hierbabuena
Producto (Macuy/Hierba mora/Quilete ; 2024, Febrero ) agredado a timeline de Producto existente Macuy/Hierba mora/Quilete
Producto (Chile pimiento fresco ; 2024, Febrero ) agredado a timeline de Producto existente Chile pimiento fresco
Producto (Pepinos y pepinillos, frescos o refrigerados ; 2024, Febrero ) agredado a timeline de Producto existente Pepinos y pepinillos, frescos o refrigerados
Producto (Tomate fresco ; 2024, Febrero ) agredado a timeline de Producto existente Tomate fresco
Producto (Güisquil ; 2024, Febrero ) agredado a timeline de Producto existente Güisquil
Producto (Zanahorias ; 2024, Febrero ) agredado a timeline de Producto existente Zanahorias
Producto (Cebollas ; 2024, Febrero ) agredado a timeline de Producto existente Cebollas
Producto (Verduras frescas o refrigeradas limpias y cortadas (excluye las ensaladas) ; 2024, Febrero ) agredado a timeline de Producto existente Verduras frescas o refrigeradas limpias y cortadas (excluye las ensaladas)
Producto (Papas ; 2024, Febrero ) agredado a timeline de Producto existente Papas
Producto (Frijoles negros, secos ; 2024, Febrero ) agredado a timeline de Producto existente Frijoles negros, secos
Producto (Frijoles preparados, procesados y condimentados (enlatados o empaquetados) ; 2024, Febrero ) agredado a timeline de Producto existente Frijoles preparados, procesados y condimentados (enlatados o empaquetados)
Producto (Azúcar de caña blanca ; 2024, Febrero ) agredado a timeline de Producto existente Azúcar de caña blanca
Producto (Azúcar de caña morena ; 2024, Febrero ) agredado a timeline de Producto existente Azúcar de caña morena
Producto (Sopas instantáneas (Vaso y bolsa) ; 2024, Febrero ) agredado a timeline de Producto existente Sopas instantáneas (Vaso y bolsa)
Producto (Sal ; 2024, Febrero ) agredado a timeline de Producto existente Sal
Producto (Consomé ; 2024, Febrero ) agredado a timeline de Producto existente Consomé
Producto (Salsa de tomate (Ranchera, Queso etc.) ; 2024, Febrero ) agredado a timeline de Producto existente Salsa de tomate (Ranchera, Queso etc.)
Producto (Mayonesa  ; 2024, Febrero ) agredado a timeline de Producto existente Mayonesa
Producto (Bases para sopas  ; 2024, Febrero ) agredado a timeline de Producto existente Bases para sopas
Producto (Snacks (excluye papalinas, plataninas, yucas, malangas, etc.) ; 2024, Febrero ) agredado a timeline de Producto existente Snacks (excluye papalinas, plataninas, yucas, malangas, etc.)
Producto (Jugos de frutas líquidos  ; 2024, Febrero ) agredado a timeline de Producto existente Jugos de frutas líquidos
Producto (Jugos de frutas en polvo ; 2024, Febrero ) agredado a timeline de Producto existente Jugos de frutas en polvo
Producto (Café molido ; 2024, Febrero ) agredado a timeline de Producto existente Café molido
Producto (Café instantáneo ; 2024, Febrero ) agredado a timeline de Producto existente Café instantáneo
Producto (Agua purificada ; 2024, Febrero ) agredado a timeline de Producto existente Agua purificada
Producto (Gaseosas ; 2024, Febrero ) agredado a timeline de Producto existente Gaseosas
Producto (Desayuno o cena continental (bebida y dos acompañamientos elaborados) ; 2024, Febrero ) agredado a timeline de Producto existente Desayuno o cena continental (bebida y dos acompañamientos elaborados)
Producto (Almuerzo o cena simple (bebida, carne de pollo y acompañamiento) excluye gaseosa ; 2024, Febrero ) agredado a timeline de Producto existente Almuerzo o cena simple (bebida, carne de pollo y acompañamiento) excluye gaseosa
Producto (Tamales y paches  ; 2024, Febrero ) agredado a timeline de Producto existente Tamales y paches
Producto (Piezas de pollo individual o entero (sin acompañamiento) ; 2024, Febrero ) agredado a timeline de Producto existente Piezas de pollo individual o entero (sin acompañamiento)
Producto (Atoles ; 2024, Febrero ) agredado a timeline de Producto existente Atoles
Producto (Arroz corriente ; 2024, Marzo ) agredado a timeline de Producto existente Arroz corriente
Producto (Arroz precocido ; 2024, Marzo ) agredado a timeline de Producto existente Arroz precocido
Producto (Pan francés ; 2024, Marzo ) agredado a timeline de Producto existente Pan francés
Producto (Pan dulce ; 2024, Marzo ) agredado a timeline de Producto existente Pan dulce
Producto (Galletas dulces ; 2024, Marzo ) agredado a timeline de Producto existente Galletas dulces
Producto (Tortillas frescas ; 2024, Marzo ) agredado a timeline de Producto existente Tortillas frescas
Producto (Cereales de bolsa o caja ; 2024, Marzo ) agredado a timeline de Producto existente Cereales de bolsa o caja
Producto (Espagueti ; 2024, Marzo ) agredado a timeline de Producto existente Espagueti
Producto (Fideos en todas sus formas (Excepto macarrones y espagueti) ; 2024, Marzo ) agredado a timeline de Producto existente Fideos en todas sus formas (Excepto macarrones y espagueti)
Producto (Carne de res molida ; 2024, Marzo ) agredado a timeline de Producto existente Carne de res molida
Producto (Carne de res para asar (con y sin hueso) ; 2024, Marzo ) agredado a timeline de Producto existente Carne de res para asar (con y sin hueso)
Producto (Carne de res sin hueso (posta) ; 2024, Marzo ) agredado a timeline de Producto existente Carne de res sin hueso (posta)
Producto (Carne de res con hueso para cocido ; 2024, Marzo ) agredado a timeline de Producto existente Carne de res con hueso para cocido
Producto (Posta de cerdo sin hueso  ; 2024, Marzo ) agredado a timeline de Producto existente Posta de cerdo sin hueso
Producto (Carne de pollo blanco ; 2024, Marzo ) agredado a timeline de Producto existente Carne de pollo blanco
Producto (Carne de pollo amarillo  ; 2024, Marzo ) agredado a timeline de Producto existente Carne de pollo amarillo
Producto (Salchichas y productos similares de carne ; 2024, Marzo ) agredado a timeline de Producto existente Salchichas y productos similares de carne
Producto (Jamón (pollo, res, cerdo, mixto, etc.) ; 2024, Marzo ) agredado a timeline de Producto existente Jamón (pollo, res, cerdo, mixto, etc.)
Producto (Longanizas y chorizos (de todo tipo) ; 2024, Marzo ) agredado a timeline de Producto existente Longanizas y chorizos (de todo tipo)
Producto (Leche entera líquida industrializada ; 2024, Marzo ) agredado a timeline de Producto existente Leche entera líquida industrializada
Producto (Crema artesanal ; 2024, Marzo ) agredado a timeline de Producto existente Crema artesanal
Producto (Crema industrializada ; 2024, Marzo ) agredado a timeline de Producto existente Crema industrializada
Producto (Queso fresco (Incluye el queso supercremoso) ; 2024, Marzo ) agredado a timeline de Producto existente Queso fresco (Incluye el queso supercremoso)
Producto (Huevos de gallina de granja ; 2024, Marzo ) agredado a timeline de Producto existente Huevos de gallina de granja
Producto (Aceite vegetal mixtos ; 2024, Marzo ) agredado a timeline de Producto existente Aceite vegetal mixtos
Producto (Margarina vegetal regular ; 2024, Marzo ) agredado a timeline de Producto existente Margarina vegetal regular
Producto (Aguacates frescos ; 2024, Marzo ) agredado a timeline de Producto existente Aguacates frescos
Producto (Bananos frescos ; 2024, Marzo ) agredado a timeline de Producto existente Bananos frescos
Producto (Plátanos frescos ; 2024, Marzo ) agredado a timeline de Producto existente Plátanos frescos
Producto (Papayas frescas ; 2024, Marzo ) agredado a timeline de Producto existente Papayas frescas
Producto (Limones y limas frescas ; 2024, Marzo ) agredado a timeline de Producto existente Limones y limas frescas
Producto (Manzanas frescas ; 2024, Marzo ) agredado a timeline de Producto existente Manzanas frescas
Producto (Lechuga, achicoria y rugula, fresca o refrigerada ; 2024, Marzo ) agredado a timeline de Producto existente Lechuga, achicoria y rúgula, fresca o refrigerada
Producto (Apio  ; 2024, Marzo ) agredado a timeline de Producto existente Apio
Producto (Cilantro, perejil y hierbabuena ; 2024, Marzo ) agredado a timeline de Producto existente Cilantro, perejil y hierbabuena
Producto (Macuy/Hierba mora/Quilete ; 2024, Marzo ) agredado a timeline de Producto existente Macuy/Hierba mora/Quilete
Producto (Chile pimiento fresco ; 2024, Marzo ) agredado a timeline de Producto existente Chile pimiento fresco
Producto (Pepinos y pepinillos, frescos o refrigerados ; 2024, Marzo ) agredado a timeline de Producto existente Pepinos y pepinillos, frescos o refrigerados
Producto (Tomate fresco ; 2024, Marzo ) agredado a timeline de Producto existente Tomate fresco
Producto (Güisquil ; 2024, Marzo ) agredado a timeline de Producto existente Güisquil
Producto (Zanahorias ; 2024, Marzo ) agredado a timeline de Producto existente Zanahorias
Producto (Cebollas ; 2024, Marzo ) agredado a timeline de Producto existente Cebollas
Producto (Verduras frescas o refrigeradas limpias y cortadas (excluye las ensaladas) ; 2024, Marzo ) agredado a timeline de Producto existente Verduras frescas o refrigeradas limpias y cortadas (excluye las ensaladas)
Producto (Papas ; 2024, Marzo ) agredado a timeline de Producto existente Papas
Producto (Frijoles negros, secos ; 2024, Marzo ) agredado a timeline de Producto existente Frijoles negros, secos
Producto (Frijoles preparados, procesados y condimentados (enlatados o empaquetados) ; 2024, Marzo ) agredado a timeline de Producto existente Frijoles preparados, procesados y condimentados (enlatados o empaquetados)
Producto (Azúcar de caña blanca ; 2024, Marzo ) agredado a timeline de Producto existente Azúcar de caña blanca
Producto (Azúcar de caña morena ; 2024, Marzo ) agredado a timeline de Producto existente Azúcar de caña morena
Producto (Sopas instantáneas (Vaso y bolsa) ; 2024, Marzo ) agredado a timeline de Producto existente Sopas instantáneas (Vaso y bolsa)
Producto (Sal ; 2024, Marzo ) agredado a timeline de Producto existente Sal
Producto (Consomé ; 2024, Marzo ) agredado a timeline de Producto existente Consomé
Producto (Salsa de tomate (Ranchera, Queso etc.) ; 2024, Marzo ) agredado a timeline de Producto existente Salsa de tomate (Ranchera, Queso etc.)
Producto (Mayonesa  ; 2024, Marzo ) agredado a timeline de Producto existente Mayonesa
Producto (Bases para sopas  ; 2024, Marzo ) agredado a timeline de Producto existente Bases para sopas
Producto (Snacks (excluye papalinas, plataninas, yucas, malangas, etc.) ; 2024, Marzo ) agredado a timeline de Producto existente Snacks (excluye papalinas, plataninas, yucas, malangas, etc.)
Producto (Jugos de frutas líquidos  ; 2024, Marzo ) agredado a timeline de Producto existente Jugos de frutas líquidos
Producto (Jugos de frutas en polvo ; 2024, Marzo ) agredado a timeline de Producto existente Jugos de frutas en polvo
Producto (Café molido ; 2024, Marzo ) agredado a timeline de Producto existente Café molido
Producto (Café instantáneo ; 2024, Marzo ) agredado a timeline de Producto existente Café instantáneo
Producto (Agua purificada ; 2024, Marzo ) agredado a timeline de Producto existente Agua purificada
Producto (Gaseosas ; 2024, Marzo ) agredado a timeline de Producto existente Gaseosas

In [40]:
products